# -*- coding: utf-8 -*-
"""Face_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJrFD9hemIgTjeoMZqaathWf5HKKzOQ6
"""

# 📌 Step 1: Install dependencies
!pip install opencv-python-headless

# 📌 Step 2: Import libraries
import cv2
import numpy as np
from google.colab import output
from IPython.display import display, Javascript
from base64 import b64decode
from PIL import Image

# 📌 Step 3: Define capture function
def take_photo(filename='photo.jpg', quality=0.8):
    js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = '📷 Capture Photo';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture button
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();

      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
    display(js)

    # Run the JS function we just defined
    data = output.eval_js('takePhoto({})'.format(quality))

    # Convert base64 to image
    binary = b64decode(data.split(',')[1])
    with open(filename, 'wb') as f:
        f.write(binary)
    return filename

# 📌 Step 4: Capture photo from webcam
filename = take_photo()

# 📌 Step 5: Load image
img = cv2.imread(filename)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 📌 Step 6: Load Haar Cascade
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")

# Detect faces
faces = face_cascade.detectMultiScale(gray, 1.1, 4)

# Draw rectangles
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 3)

# 📌 Step 7: Show result
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
Image.fromarray(img_rgb)